### ISSUE TITLE
What is the leading repo?

### ISSUE THREAD

**Issue by clemens-tolboom** [godot-extended-libraries/godot-plugin-refresher#11]
Visiting https://godotengine.org/asset-library/asset/248 the link repo is https://github.com/willnationsdev/godot-plugin-refresher which is behind 4 commits / 16 month older.

**Comment by willnationsdev** [comment]
Oh, whoops. Didn't realize I hadn't updated that. Yeah, the Godot extended libraries one is the official version. I'll update that asap.

**Comment by willnationsdev** [comment]
@clemens-tolboom I just submitted an update to change it, so whenever the update is approved, the GAL should have the proper version. Thanks!
