### ISSUE TITLE
can't activate this plugin in Godot 4

### ISSUE THREAD

**Issue by robochase6000** [godot-extended-libraries/godot-plugin-refresher#30]
Hey, this might be a known issue, but I was trying to get this plugin to work in Godot 4, and it would spit out an error whenever I tried to activate the plugin in my project settings.

I saw someone made a PR for this, and this fix seemed to get me going - maybe it should be merged?
https://github.com/godot-extended-libraries/godot-plugin-refresher/pull/28

**Comment by willnationsdev** [comment]
Closed via #31.
