### ISSUE TITLE
Improving the visual appeal and readablility of the plugin list

### ISSUE THREAD

**Issue by Xrayez** [godot-extended-libraries/godot-plugin-refresher#9]
Currently, the list of displayed plugins is what it actually represents: the directory names. The problem is that the names might be in `lowercase`, `UPPERCASE`, `snake_case`, `kebab-case` etc.

Do you think it would be better to retrieve the actual plugin name from `plugin.cfg`? I know that the underlying system relies on plugin names as determined by directory names, but for visual stuff this should be fine.

Somewhat related to #8.

**Comment by willnationsdev** [comment]
Yeah, that sounds pretty good to me. Would potentially make it more consistent. But if any two names conflict for some reason, we should include parentheses in the item with the actual directory name.
